version: '3.8'

services:
  db-test:
    image: postgres
    restart: always
    container_name: food-delivery-portfolio-test-container
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - ${PGPORT}:5432

networks:
  default:
    name: food-delivery-portfolio-test-network
