version: '3.8'

services:
  db-test:
    image: postgres
    restart: always
    container_name: uber-eats-test-container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

networks:
  default:
    name: uber-eats-test-network
